#!/bin/bash
# easylog - A simple logging utility.

log() {
  local level="$1"
  local message="$2"
  local timestamp=$(date '+%Y-%m-%d %H:%M:%S')

  case "$level" in
    DEBUG) [[ $VERBOSITY -ge 3 ]] && echo "$timestamp [DEBUG] $message" ;;
    INFO) [[ $VERBOSITY -ge 2 ]] && echo "$timestamp [INFO] $message" ;;
    WARN) [[ $VERBOSITY -ge 1 ]] && echo "$timestamp [WARN] $message" ;;
    ERROR) echo "$timestamp [ERROR] $message" ;;
    *) echo "$timestamp [UNKNOWN] Unknown log level: $level" ;;
  esac
}

VERBOSITY=${VERBOSITY:-0}

while getopts "v" opt; do
  case $opt in
    v) VERBOSITY=$((VERBOSITY+1)) ;;
    *) echo "Usage: easylog [-v] <level> <message>" >&2; exit 1 ;;
  esac
done

shift $((OPTIND-1))

if [ "$#" -ne 2 ]; then
    echo "Usage: easylog [-v] <level> <message>" >&2
    exit 1
fi

log "$1" "$2"
